/**
 * propsyBackendv01 API
 * propsyBackendv01 API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Customer } from './customer';
import { DeliveryPersonnel } from './deliveryPersonnel';
import { Food } from './food';
import {IRestaurant, Restaurant} from './restaurant';
import {IUser} from './user';

export enum OrderStatus {
  NEW = 'NEW',
  PAYMENT = 'PAYMENT',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  TO_PICK_UP = 'TO_PICK_UP',
  IN_DELIVERY = 'IN_DELIVERY',
  DELIVERED = 'DELIVERED'
}

export interface FoodOrder {
  id?: number;
  timeRating?: number;
  priceRating?: number;
  qualityRating?: number;
  loyaltyPoints?: number;
  addressRating?: number;
  // date?: Moment;
  price?: number;
  status?: OrderStatus;
  purchaserOpinion?: string;
  purchaserComment?: string;
  city?: string;
  phone?: string;
  address?: string;
  restaurant?: IRestaurant;
  deliveryman?: IUser;
  // purchaser?: IUser;
  // foodItems?: IFood[];
  // movements?: IFoodOrderMovement[];
}
